name: Frontend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'  # Sadece frontend klasörü değişince çalışacak
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend # Çalışma dizini frontend olarak ayarlandı
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'pnpm'
        cache-dependency-path: frontend/pnpm-lock.yaml
    - run: pnpm install
    - run: pnpm lint
    - run: pnpm build